import { Patient } from "../models/patient";

  export const mock_patients: Patient[] = [
    {
      id: "b5de",
      email: "mo@example.com",
      first_name: "Mo",
      last_name: "Smith",
      phone_number: "0553881217",
      address: "123 Main St, City",
      gender: "Male",
      nss: "123456789",
      date_of_birth: "1990-12-09",
      place_of_birth: "City",
      emergency_contact_name: "Jane Doe",
      emergency_contact_phone: "1234567891",
      medical_condition: "None",
      profile_picture: "patient-info-avatar.svg",
    },
    {
      id: "704b",
      email: "beyouna@example.com",
      first_name: "Beyouna",
      last_name: "Alami",
      phone_number: "0791172962",
      address: "456 Elm St, City",
      gender: "Female",
      nss: "099909090",
      date_of_birth: "1985-12-04",
      place_of_birth: "City",
      emergency_contact_name: "John Doe",
      emergency_contact_phone: "0553881218",
      medical_condition: "Asthma",
      profile_picture: "patient-info-avatar.svg",
    },
    {
      id: "bc88",
      email: "amel@example.com",
      first_name: "Amel",
      last_name: "Sadoun",
      phone_number: "0553881217",
      address: "789 Pine St, City",
      gender: "Female",
      nss: "223344556",
      date_of_birth: "2002-04-12",
      place_of_birth: "City",
      emergency_contact_name: "David Smith",
      emergency_contact_phone: "0553881219",
      medical_condition: "Diabetes",
      profile_picture: "patient-info-avatar.svg",
    },
    {
      id: "d784",
      email: "galk.wahed@example.com",
      first_name: "Galk",
      last_name: "Wahed",
      phone_number: "0553881217",
      address: "321 Cedar Ave, City",
      gender: "Male",
      nss: "334455667",
      date_of_birth: "1998-11-02",
      place_of_birth: "Town",
      emergency_contact_name: "Sarah Wahed",
      emergency_contact_phone: "0777888999",
      medical_condition: "High Blood Pressure",
      profile_picture: "patient-info-avatar.svg",
    },
    {
      id: "7364",
      email: "dd@example.com",
      first_name: "Dddd",
      last_name: "Efgh",
      phone_number: "0777888999",
      address: "45 Oak Lane, Village",
      gender: "Male",
      nss: "556677889",
      date_of_birth: "1995-06-15",
      place_of_birth: "Village",
      emergency_contact_name: "Rami Efgh",
      emergency_contact_phone: "0666555444",
      medical_condition: "None",
      profile_picture: "patient-info-avatar.svg",
    },
    {
      id: "c123",
      email: "amina.toumi@example.com",
      first_name: "Amina",
      last_name: "Toumi",
      phone_number: "0667788990",
      address: "45 Rue Nationale, Algiers",
      gender: "Female",
      nss: "112233445",
      date_of_birth: "2000-01-15",
      place_of_birth: "Algiers",
      emergency_contact_name: "Karim Toumi",
      emergency_contact_phone: "0558899901",
      medical_condition: "None",
      profile_picture: "patient-info-avatar.svg",
    },
    {
      id: "d456",
      email: "said.karim@example.com",
      first_name: "Said",
      last_name: "Karim",
      phone_number: "0776655443",
      address: "12 Boulevard Oran, Oran",
      gender: "Male",
      nss: "778899112",
      date_of_birth: "1995-06-10",
      place_of_birth: "Oran",
      emergency_contact_name: "Layla Karim",
      emergency_contact_phone: "0776655444",
      medical_condition: "Heart Condition",
      profile_picture: "patient-info-avatar.svg",
    },
    {
      id: "e789",
      email: "nour.benali@example.com",
      first_name: "Nour",
      last_name: "Benali",
      phone_number: "0677889922",
      address: "78 Avenue Constantine, Constantine",
      gender: "Female",
      nss: "990011223",
      date_of_birth: "1998-09-25",
      place_of_birth: "Constantine",
      emergency_contact_name: "Hassan Benali",
      emergency_contact_phone: "0677889933",
      medical_condition: "Allergies",
      profile_picture: "patient-info-avatar.svg",
    },
  ];
  